#!/bin/sh
set -eu

cd /usr/pkgsrc
find . -maxdepth 3 -mindepth 3 -name Makefile \
     -exec grep -F --files-with-matches mk/haskell.mk {} + |
    sed -e 's,\./,,;s,/Makefile$,,' |
    grep -E -v '^wip/' |
    sort -u |
    while read -r pkgdir; do # For each package using mk/haskell.mk
        # Self-cycle to make it appear in the result even if it has no
        # dependencies
        echo "${pkgdir} ${pkgdir}"
        (cd "${pkgdir}" && bmake show-vars VARNAMES="BUILD_DEPENDS TOOL_DEPENDS DEPENDS") |
            tr ' ' '\n' |
            cut -d ':' -f 2 |
            sed 's|../../||' |
            sort -u |
            while read -r pkgdep; do
                # Omit the dependency if it does not use mk/haskell.mk
                if grep -F mk/haskell.mk "${pkgdep}/Makefile" >/dev/null 2>&1; then
                    # tsort's notation: ${pkgdir} depends on ${pkgdep}
                    echo "${pkgdep} ${pkgdir}"
                fi
            done
    done |
    tsort
