#!/bin/sh
set -eu

REVBUMP=revbump.py
if ! ${REVBUMP} -h >/dev/null 2>&1; then
    echo >&2 "$0: ${REVBUMP} isn't installed or working"
    exit 1
fi

if [ ! -e /tmp/allbump ]; then
    echo "==> Searching for packages that need revbump"
    cd /usr/pkgsrc
    find . -maxdepth 3 -mindepth 3 -name Makefile \
         -exec grep -F --files-with-matches mk/haskell.mk {} + | \
        sed -e 's,\./,,;s,/Makefile$,,' | \
        grep -E -v '^wip/' | \
        sort -u | tee /tmp/allbump
fi

if [ ! -e /tmp/revbump.done ]; then
    echo "==> Bumping Makefile and buildlink3.mk"
    while read pkgdir; do
        echo "${pkgdir}"
        ${REVBUMP} -x "${pkgdir}"
    done < /tmp/allbump
    touch /tmp/revbump.done
fi

echo "==> Getting cvs diff"
# shellcheck disable=SC2046
cvs -q diff -u $(cat /tmp/allbump) | less

read -p "Okay to commit it? Type Enter to proceed:" dummy
# shellcheck disable=SC2046
cvs ci $(cat /tmp/allbump)

rm -f /tmp/allbump /tmp/revbump.done
