#!/bin/sh
set -eu

if [ ! -e /tmp/allbump ]; then
    echo "==> Searching for packages that need revbump"
    cd /usr/pkgsrc
    find . -maxdepth 3 -mindepth 3 -name Makefile \
         -exec grep -F --files-with-matches mk/haskell.mk {} + | \
        sed -e 's,\./,,;s,/Makefile$,,' | \
        grep -E -v '^wip/' | \
        sort -u | tee /tmp/allbump
fi

if [ ! -e /tmp/revbump.done ]; then
    echo "==> Bumping Makefile"
    revbump < /tmp/allbump | tee /tmp/revbump.manual
    touch /tmp/revbump.done
fi

echo "=> Checking if there are any packages that failed to auto-bump"
if [ -s /tmp/revbump.manual ]; then
    echo "=> The following packages need manual revbump. Remove /tmp/revbump.manual and re-run $0 when you are done."
    cat /tmp/revbump.manual
    exit 1
fi

if [ ! -e /tmp/blbump.done ]; then
    echo "==> Bumping buildlink3.mk"
    blbump < /tmp/allbump | tee /tmp/blbump.manual
    touch /tmp/blbump.done
fi

echo "=> Checking if there are any packages that failed to auto-bump"
if [ -s /tmp/blbump.manual ]; then
    echo "=> The following packages need manual blbump. Remove /tmp/blbump.manual and re-run $0 when you are done."
    cat /tmp/blbump.manual
    exit 1
fi

echo "==> Getting cvs diff"
cvs -q diff -u $(cat /tmp/allbump) >/tmp/revbump.diff || true

echo "==> Cleaning up unintended changes"
check-cvs-diff /tmp/revbump.diff

cvs -q diff -u $(cat /tmp/allbump) | less
cvs ci $(cat /tmp/allbump)

rm -f /tmp/allbump /tmp/revbump.manual /tmp/blbump.manual /tmp/revbump.diff
