#!/usr/bin/env bash
set -eu

if pkg_info -qe ghc; then
    packages=$(pkg_info -qr ghc | sort)
else
    echo "GHC seems to have been uninstalled. Checking for leftovers..."
    declare -a pkgs=()
    while read -r pkgname _description; do
        if pkg_info -qN "$pkgname" | grep -qE '^ghc-[^-]+$'; then
            pkgs+=("$pkgname")
        fi
    done < <(pkg_info)
    packages="${pkgs[*]}"
fi

# But don't uninstall cabal2pkg.
packages=$(echo "$packages" | grep -Fv "cabal2pkg")

(
    echo "These packages are to be deleted. Are you okay with this?"
    echo "(You'll be prompted after quitting the pager.)"
    echo "--"
    echo "${packages}"
) | ${PAGER:-less}

echo -n "Type y/n: "
read -r -n 1 key
case "$key" in
    y)
        echo
        echo "echo \"\$packages\" | sudo xargs pkg_delete -fv"
        echo "${packages}" | sudo xargs pkg_delete -fv;;
    *)
        exit
esac
